# Generated by Django 4.0 on 2022-11-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(max_length=13)),
                ('pollingunit_uniqueid', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='Announced_lga_results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lga_name', models.CharField(default='', max_length=50)),
                ('party_abbreviation', models.CharField(default='', max_length=4)),
                ('party_score', models.IntegerField()),
                ('entered_by_user', models.CharField(default='', max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Announced_pu_results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_unit_uniqueid', models.CharField(default='', max_length=50, null=True)),
                ('party_abbreviation', models.CharField(default='', max_length=4, null=True)),
                ('party_score', models.IntegerField(null=True)),
                ('entered_by_user', models.CharField(default='', max_length=50, null=True)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Announced_state_results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(default='', max_length=50, null=True)),
                ('party_abbreviation', models.CharField(default='', max_length=4, null=True)),
                ('party_score', models.IntegerField(null=True)),
                ('entered_by_user', models.CharField(default='', max_length=50, null=True)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Announced_ward_results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(default='', max_length=50, null=True)),
                ('party_abbreviation', models.CharField(default='', max_length=4, null=True)),
                ('party_score', models.IntegerField(null=True)),
                ('entered_by_user', models.CharField(default='', max_length=50, null=True)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lga_id', models.IntegerField(null=True)),
                ('lga_name', models.CharField(default='', max_length=50, null=True)),
                ('state_id', models.IntegerField(null=True)),
                ('lga_description', models.TextField(default='', max_length=255, null=True)),
                ('entered_by_user', models.CharField(default='', max_length=50, null=True)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partyid', models.CharField(max_length=11, null=True)),
                ('partyname', models.CharField(max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polling_unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_unit_id', models.IntegerField(null=True)),
                ('ward_id', models.IntegerField(null=True)),
                ('lga_id', models.IntegerField(null=True)),
                ('uniquewardid', models.IntegerField(null=True)),
                ('polling_unit_number', models.CharField(default='', max_length=50, null=True)),
                ('polling_unit_name', models.CharField(default='', max_length=50, null=True)),
                ('polling_unit_description', models.TextField(default='')),
                ('lat', models.CharField(default='', max_length=255, null=True)),
                ('long', models.CharField(default='', max_length=255, null=True)),
                ('entered_by_user', models.CharField(default='', max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_id', models.IntegerField(null=True)),
                ('ward_name', models.CharField(max_length=50, null=True)),
                ('lga_id', models.IntegerField(null=True)),
                ('ward_description', models.TextField(default='')),
                ('entered_by_user', models.CharField(default='', max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
    ]
