# Generated by Django 4.0 on 2022-11-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polling_unit',
            name='lga_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
